@startuml 
interface Door {
    void lock()

    void unlock()

    void open()

    void close()
}
interface ISensor {
  void proximityCallBack()
}

interface ITime {
  void timeOutCallback()
}
SensingDoor --|> Door
SensingDoor --|> ISensor
TimedDoor --|> ITime
TimedDoor  --|> Door
@enduml